In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [16]:
for x in a:
    print(x)

1
2
3


In [27]:
a+[4]

array([5, 6, 7])

In [28]:
a+[5,8,0]

array([ 6, 10,  3])

In [29]:
2*a

array([2, 4, 6])

In [30]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [32]:
np.dot(a,a)

14

In [33]:
a.dot(a)

14

In [35]:
a @ a

14

In [41]:
aNorm=np.sqrt((a**2).sum())

In [42]:
aNorm

3.7416573867739413

In [43]:
np.linalg.norm(a)

3.7416573867739413

In [54]:
b=np.array([[1,2],[3,5]])

In [55]:
b

array([[1, 2],
       [3, 5]])

In [58]:
b[0][1]

2

In [59]:
b[0,1]

2

In [60]:
b[:,0]

array([1, 3])

In [61]:
b[0,:]

array([1, 2])

In [62]:
b.T

array([[1, 3],
       [2, 5]])

In [63]:
np.exp(b)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692, 148.4131591 ]])

In [64]:
b.dot(b)

array([[ 7, 12],
       [18, 31]])

In [65]:
np.linalg.det(b)

-1.0000000000000004

In [69]:
np.linalg.inv(b)

array([[-5.,  2.],
       [ 3., -1.]])

In [70]:
np.trace(b)

6

In [71]:
np.diag(b)

array([1, 5])

In [72]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [73]:
np.linalg.eig(b)

(array([-0.16227766,  6.16227766]), array([[-0.86460354, -0.36126098],
        [ 0.50245469, -0.93246475]]))

In [75]:
a=np.array([[1,2],[3,4]])
b=np.array([4,5])
np.linalg.solve(a,b)

array([-3. ,  3.5])

In [76]:
np.linalg.inv(a).dot(b)

array([-3. ,  3.5])

In [77]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [79]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.random.random()

0.9572880756631855

In [84]:
np.random.random([3,3])

array([[0.78597905, 0.51458876, 0.29208431],
       [0.36039875, 0.06903303, 0.74720464],
       [0.2737959 , 0.51038675, 0.62584992]])

In [82]:
np.random.randn(3,3)

array([[-0.03504177,  1.62006318,  0.7779145 ],
       [-2.35897682, -0.76025497, -0.71622335],
       [-0.33564079,  0.87194391, -2.35662706]])

In [89]:
np.random.randn(10000).mean()

0.0030110208343192843

In [91]:
np.random.randn(10000).var()

1.0067775413815274

In [92]:
np.random.randn(10000).std()

0.9919492414975191

In [93]:
0.9919492414975191*0.9919492414975191

0.9839632977075033

In [94]:
c=np.random.randn(2,3)

In [96]:
c.mean(axis=0)

array([-0.85046162, -0.48606739, -0.11452369])

In [97]:
c.mean(axis=1)

array([-0.8945332 , -0.07283527])

In [98]:
c.mean()

-0.4836842329036049

In [102]:
np.cov(c.T)

array([[ 2.26233487, -2.91572511, -1.96839369],
       [-2.91572511,  3.75782251,  2.53689008],
       [-1.96839369,  2.53689008,  1.71264376]])

In [103]:
np.random.randint(0,10,[2,2])

array([[9, 3],
       [1, 3]])